export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'moredocs',
      description: 'Open Source Nuxt Content template built with shadcn-vue.',
      ogImage: '/hero.png',
    },
    theme: {
      customizable: true,
      color: 'violet',
      radius: 0.5,
    },
    header: {
      title: 'moredocs',
      showTitle: true,
      logo: {
        light: '/logo.svg',
        dark: '/logo-dark.svg',
      },
      darkModeToggle: true,
      nav: [{
        icon: 'lucide:book',
        title: 'Docs',
        links: [{
          icon: 'lucide:info',
          title: 'Getting Started',
          to: '/getting-started',
          description: 'Start building your documentation',
        }, {
          icon: 'lucide:code',
          title: 'API',
          to: '/api',
          description: 'Discover the configurations and exposed APIs.',
          target: '_self',
        }],
      }, {
        icon: 'lucide:cat',
        title: 'Credits',
        links: [{
          icon: 'vscode-icons:file-type-js',
          title: 'shadcn-ui',
          to: 'https://ui.shadcn.com/',
          description: 'For the beautiful component design & docs design',
          target: '_blank',
        }, {
          icon: 'vscode-icons:file-type-vue',
          title: 'shadcn-vue',
          to: 'https://www.shadcn-vue.com/',
          description: 'For the vue port of shadcn-ui & some docs component source',
          target: '_blank',
        }, {
          icon: 'vscode-icons:file-type-nuxt',
          title: 'Docus',
          to: 'https://docus.dev/',
          description: 'For inspiration & some docs component source',
          target: '_blank',
        }, {
          icon: 'vscode-icons:file-type-nuxt',
          title: 'Nuxt Content',
          to: 'https://content.nuxt.com/',
          description: 'Content made easy for Vue Developers',
          target: '_blank',
        }],
      }, {
        icon: 'lucide:copy',
        title: 'Get',
        to: '/getting-started/installation',
        target: '_self',
      }],
      links: [{
        icon: 'lucide:github',
        to: 'https://github.com/Catventurist/moredocs',
        target: '_blank',
      }],
    },
    aside: {
      useLevel: true,
      collapse: false,
    },
    main: {
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
        'github': 'lucide:github',
        'linkedin': 'lucide:linkedin',
        'x': 'lucide:x'
      },
    },
    footer: {
      credits: 'Copyright © 2024',
      links: [
        {
          icon: 'vscode-icons:file-type-vue',
          title: 'shadcn-vue',
          to: 'https://www.shadcn-vue.com/',
          target: '_blank',
        },
        {
          icon: 'lucide:github',
          title: 'Github',
          to: 'https://github.com/Catventurist/moredocs',
          target: '_blank',
        },
      ],
    },
    toc: {
      enable: true,
      title: 'On This Page',
      links: [{
        title: 'Star on GitHub',
        icon: 'lucide:star',
        to: 'https://github.com/Catventurist/moredocs',
        target: '_blank',
      }],
    },
    search: {
      enable: true,
      inAside: false,
    },
    insta: {
      links: [{
        icon: 'lucide:home',
        title: 'Home',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:compass',
        title: 'Explore',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:video',
        title: 'Video',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:message-circle',
        title: 'Messages',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:bell',
        title: 'Notifications',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:circle-plus',
        title: 'Create',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:settings',
        title: 'Settings',
        to: '/',
        target: '_self',
      }]
    },
    dash: {
      links: [{
        icon: 'lucide:home',
        title: 'Home',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:shopping-bag',
        title: 'Orders',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:package',
        title: 'Products',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:users',
        title: 'Customers',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:line-chart',
        title: 'Analytics',
        to: '/',
        target: '_self',
      }, {
        icon: 'lucide:settings',
        title: 'Settings',
        to: '/',
        target: '_self',
      }],
      promo: [{
        icon: 'lucide:heart',
        title: 'Freedom',
        description: 'Is the best',
        content: 'Try it out',
        to: '/',
        target: '_self',
      }],
    },
  },
});
